<?php

namespace AppBundle\Repository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll() {
        $qb = $this->createQueryBuilder('f')
                  ->orderBy('f.datedujour', 'DESC')
                 ->orderBy('f.journalist', 'DESC')
                 ->orderBy('f.id', 'DESC');
          return $qb->getQuery()->getResult();
    }

    
}
