<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
    /**
     * Récupération du nombre de votes de l'auditeur sur l'annonce
     */
    public function findOneByUserAnnonce($user, $annonce) {
        $query = $this->getEntityManager()
                        ->createQuery(
                                'SELECT v  FROM AppBundle:Vote v
                                WHERE v.auteur = :userId AND v.annonce = :annonceId'
                        )->setParameter('userId', $user)
                        ->setParameter('annonceId', $annonce);
        return sizeof($query->getResult());
    }
    
     /**
     *Récupération du nombre de votes de l'auditeur sur l'émission
     */
    public function findOneByUserPassage($user, $passage) {
        $query = $this->getEntityManager()
                        ->createQuery(
                                'SELECT v  FROM AppBundle:Vote v
                                WHERE v.auteur = :userId AND v.passage = :passageId'
                        )->setParameter('userId', $user)
                        ->setParameter('passageId', $passage);
        return sizeof($query->getResult());
    }
    
     /**
     *Récupération du nombre de votes de l'auditeur sur l'émission
     */
    public function findOneByUserTemoignage($user, $temoignage) {
        $query = $this->getEntityManager()
                        ->createQuery(
                                'SELECT v  FROM AppBundle:Vote v
                                WHERE v.auteur = :userId AND v.passage = :temoignageId'
                        )->setParameter('userId', $user)
                        ->setParameter('temoignageId', $temoignage);
        return sizeof($query->getResult());
    }
}
