# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
        rie_user_provider.class: Application\Sonata\UserBundle\Security\Core\User\FOSUBUserProvider
services:   
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
           - { name: form.type, alias: app_user_registration }
       
    admin.annonce:
        class: AppBundle\Admin\AnnonceAdmin
        arguments: [~, AppBundle\Entity\Annonce, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Annonce }
    admin.emission:
        class: AppBundle\Admin\EmissionAdmin
        arguments: [~, AppBundle\Entity\Emission, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Emission }
        public: true
    admin.espace:
        class: AppBundle\Admin\EspaceAdmin
        arguments: [~, AppBundle\Entity\Espace, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Espace }
        public: true
    admin.passage:
        class: AppBundle\Admin\PassageAdmin
        arguments: [~, AppBundle\Entity\Passage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Passage }
        public: true
    admin.film:
        class: AppBundle\Admin\FilmAdmin
        arguments: [~, AppBundle\Entity\Film, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Film }
        public: true
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
        public: true
    admin.temoignage:
        class: AppBundle\Admin\TemoignageAdmin
        arguments: [~, AppBundle\Entity\Temoignage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Temoignage }
        public: true
    admin.enquiry:
        class: AppBundle\Admin\EnquiryAdmin
        arguments: [~, AppBundle\Entity\Enquiry, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Message }
        public: true

    rie_user_provider:
        class: "%rie_user_provider.class%"
            #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebookUid}]