<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    /**
     * Récupération du nombre de votes de l'auditeur sur l'annonce
     */
    public function findByGroup($group) {

        $query = $this->getEntityManager()
                        ->createQuery(
                                'SELECT u  FROM ApplicationSonataUserBundle:User u
                                WHERE v.group = :group'
                        )->setParameter('group', $group);
        return $query->getResult();
    }
	public function findAll() {
        $query = $this->getEntityManager()
                        ->createQuery(
                                'SELECT u  FROM ApplicationSonataUserBundle:User u'
                        ) ->orderBy('u.username', 'ASC');
        return $query->getResult();
    }

    // Liste des auteurs de sermons
    public function findAllOrderedByName()
    {
        $qb = $this->createQueryBuilder('u')
                ->leftJoin('u.sermons', 's')
                ->where('s.id is not null')
                ->orderBy('s.datedujour');
               
        return $qb->getQuery() ->getResult();
    }

}
